// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var Caml_obj = require("bs-platform/lib/js/caml_obj.js");
var Belt_Array = require("bs-platform/lib/js/belt_Array.js");

function set(instance, key, value) {
  return Belt_Array.map(instance, (function (k, v) {
                if (Caml_obj.caml_equal(k, key)) {
                  return /* tuple */[
                          k,
                          value
                        ];
                } else {
                  return /* tuple */[
                          k,
                          v
                        ];
                }
              }));
}

function get(instance, key) {
  return Belt_Array.getBy(instance, (function (param) {
                return Caml_obj.caml_equal(param[0], key);
              }));
}

exports.set = set;
exports.get = get;
/* No side effect */
