// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';


function str(prim) {
  return prim;
}

var $$Location = /* module */[];

function getData(param) {
  return (document.querySelector("input[type='hidden']").value);
}

var Dealer = /* module */[/* getData */getData];

exports.str = str;
exports.$$Location = $$Location;
exports.Dealer = Dealer;
/* No side effect */
