// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var Json_decode = require("@glennsl/bs-json/src/Json_decode.bs.js");
var Json_encode = require("@glennsl/bs-json/src/Json_encode.bs.js");

function response(json) {
  return /* record */[/* id */Json_decode.field("id", Json_decode.string, json)];
}

var Decode = /* module */[/* response */response];

function reg_user(username, email, password, repeat_password) {
  return Json_encode.object_(/* :: */[
              /* tuple */[
                "username",
                username
              ],
              /* :: */[
                /* tuple */[
                  "email",
                  email
                ],
                /* :: */[
                  /* tuple */[
                    "password",
                    password
                  ],
                  /* :: */[
                    /* tuple */[
                      "repeat_password",
                      repeat_password
                    ],
                    /* [] */0
                  ]
                ]
              ]
            ]);
}

function log_user(username, password) {
  return Json_encode.object_(/* :: */[
              /* tuple */[
                "username",
                username
              ],
              /* :: */[
                /* tuple */[
                  "password",
                  password
                ],
                /* [] */0
              ]
            ]);
}

var Encode = /* module */[
  /* reg_user */reg_user,
  /* log_user */log_user
];

exports.Decode = Decode;
exports.Encode = Encode;
/* No side effect */
