// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReasonReactRouter = require("reason-react/src/ReasonReactRouter.js");
var Layout$ReactHooksTemplate = require("./components/Layout.bs.js");
var Pages__404$ReactHooksTemplate = require("./pages/Pages__404.bs.js");
var Pages__Index$ReactHooksTemplate = require("./pages/Pages__Index.bs.js");
var Pages__Signin$ReactHooksTemplate = require("./pages/Pages__Signin.bs.js");
var Pages__Signup$ReactHooksTemplate = require("./pages/Pages__Signup.bs.js");

function Router(Props) {
  var url = ReasonReactRouter.useUrl(undefined, /* () */0);
  var match = url[/* path */0];
  var tmp;
  var exit = 0;
  if (match) {
    if (match[0] === "auth") {
      var match$1 = match[1];
      if (match$1) {
        switch (match$1[0]) {
          case "signin" : 
              if (match$1[1]) {
                exit = 1;
              } else {
                tmp = React.createElement(Pages__Signin$ReactHooksTemplate.make, { });
              }
              break;
          case "signup" : 
              if (match$1[1]) {
                exit = 1;
              } else {
                tmp = React.createElement(Pages__Signup$ReactHooksTemplate.make, { });
              }
              break;
          default:
            exit = 1;
        }
      } else {
        exit = 1;
      }
    } else {
      exit = 1;
    }
  } else {
    tmp = React.createElement(Pages__Index$ReactHooksTemplate.make, { });
  }
  if (exit === 1) {
    tmp = React.createElement(Pages__404$ReactHooksTemplate.make, {
          path: url[/* path */0]
        });
  }
  return React.createElement(Layout$ReactHooksTemplate.make, {
              children: tmp
            });
}

var make = Router;

exports.make = make;
/* react Not a pure module */
