// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Helpers$ReactHooksTemplate = require("../Helpers.bs.js");

function Pages__Collection(Props) {
  Props.modelName;
  Helpers$ReactHooksTemplate.useState(/* array */[]);
  React.useEffect((function () {
          return undefined;
        }), ([]));
  return React.createElement("div", {
              className: "content__posts"
            });
}

var make = Pages__Collection;

exports.make = make;
/* react Not a pure module */
