// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var Json = require("@glennsl/bs-json/src/Json.bs.js");
var Fetch = require("bs-fetch/src/Fetch.js");
var React = require("react");
var Caml_option = require("bs-platform/lib/js/caml_option.js");
var ReasonReactRouter = require("reason-react/src/ReasonReactRouter.js");
var JMySon$ReactHooksTemplate = require("../JMySon.bs.js");
var Helpers$ReactHooksTemplate = require("../Helpers.bs.js");
var AuthLayout$ReactHooksTemplate = require("../components/AuthLayout.bs.js");
var Form__Input$ReactHooksTemplate = require("../components/Form__Input.bs.js");

function textUnder(param) {
  return React.createElement("p", {
              className: "auth__form__text"
            }, Helpers$ReactHooksTemplate.str("Don't have an account yet?"), React.createElement("br", undefined), React.createElement("a", {
                  className: "auth__form__text__link",
                  href: "/auth/signup"
                }, Helpers$ReactHooksTemplate.str("Register here!")));
}

function Pages__Signin(Props) {
  return React.createElement(AuthLayout$ReactHooksTemplate.make, {
              title: "signin",
              children: null,
              onSubmit: (function (e) {
                  var username = e.currentTarget.username.value;
                  var password = e.currentTarget.password.value;
                  fetch(window.location.origin + "/auth/signin", Fetch.RequestInit[/* make */0](/* Post */2, {
                                    "Content-Type": "application/json"
                                  }, Caml_option.some(Json.stringify(JMySon$ReactHooksTemplate.Encode[/* log_user */1](username, password))), undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined)(/* () */0)).then((function (prim) {
                              return prim.json();
                            })).then((function (x) {
                            return Promise.resolve(JMySon$ReactHooksTemplate.Decode[/* auth_response */0](x));
                          })).then((function (r) {
                          console.log(r);
                          ReasonReactRouter.push("/");
                          return Promise.resolve(r);
                        }));
                  return /* () */0;
                }),
              btnValue: "Signin",
              textUnder: textUnder
            }, React.createElement(Form__Input$ReactHooksTemplate.make, {
                  name: "username",
                  type_: "text",
                  placeholder: "username",
                  label: "username"
                }), React.createElement(Form__Input$ReactHooksTemplate.make, {
                  name: "password",
                  type_: "password",
                  placeholder: "password",
                  label: "password"
                }));
}

var make = Pages__Signin;

exports.textUnder = textUnder;
exports.make = make;
/* react Not a pure module */
