// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Helpers$ReactHooksTemplate = require("../Helpers.bs.js");

function Pages__Index(Props) {
  return React.createElement("div", {
              className: "content__index"
            }, React.createElement("h1", {
                  className: "title"
                }, Helpers$ReactHooksTemplate.str("DerivedCMS")));
}

var make = Pages__Index;

exports.make = make;
/* react Not a pure module */
