// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Belt_List = require("bs-platform/lib/js/belt_List.js");
var Helpers$ReactHooksTemplate = require("../Helpers.bs.js");

var styles = {
  height: "100vh",
  width: "100vw"
};

function Pages__404(Props) {
  var path = Props.path;
  var route = window.location.origin + ("/" + Belt_List.toArray(path).join("/"));
  return React.createElement("div", {
              style: styles
            }, Helpers$ReactHooksTemplate.str("404"), React.createElement("br", undefined), Helpers$ReactHooksTemplate.str(route), React.createElement("br", undefined), Helpers$ReactHooksTemplate.str("Not found"));
}

var make = Pages__404;

exports.styles = styles;
exports.make = make;
/* react Not a pure module */
