// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Helpers$ReactHooksTemplate = require("../Helpers.bs.js");

function Pages__Index(Props) {
  return React.createElement("div", undefined, React.createElement("h1", undefined, Helpers$ReactHooksTemplate.str("Hello index!")));
}

var make = Pages__Index;

exports.make = make;
/* react Not a pure module */
