// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var $$Array = require("bs-platform/lib/js/array.js");
var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var Belt_Array = require("bs-platform/lib/js/belt_Array.js");
var PromiseMonad = require("bs-promise-monad/src/PromiseMonad.bs.js");
var JMySon$ReactHooksTemplate = require("../../JMySon.bs.js");
var Helpers$ReactHooksTemplate = require("../../Helpers.bs.js");

function fetchItems(dispatch, collection, min, max) {
  return PromiseMonad.$great$great$pipe(PromiseMonad.$great$great$eq(PromiseMonad.$great$great$eq(PromiseMonad.$great$great$eq(fetch("/db_api/selected/" + (String(collection) + ("/?min=" + (String(min) + ("&max=" + (String(max) + "")))))), (function (prim) {
                            return prim.json();
                          })), (function (res) {
                        return PromiseMonad.$$return(JMySon$ReactHooksTemplate.Decode[/* items_response */5](res));
                      })), (function (x) {
                    return PromiseMonad.$$return(Curry._1(dispatch, /* Add */Block.__(0, [x[/* data */0]])));
                  })), (function (err) {
                return PromiseMonad.$$return((console.error(err), /* () */0));
              }));
}

function Pages__Collection__Items(Props) {
  var collection = Props.collection;
  var match = React.useReducer((function (oldItems, action) {
          if (action.tag) {
            return action[0];
          } else {
            return $$Array.concat(/* :: */[
                        action[0],
                        /* :: */[
                          oldItems,
                          /* [] */0
                        ]
                      ]);
          }
        }), /* array */[]);
  var dispatch = match[1];
  React.useEffect((function () {
          fetchItems(dispatch, collection, 0, 60);
          return undefined;
        }), ([]));
  return React.createElement("section", {
              className: "content__items"
            }, Belt_Array.mapWithIndex(match[0], (function (i, fields) {
                    return React.createElement("ul", {
                                key: String(i)
                              }, React.createElement("br", undefined), Belt_Array.mapWithIndex(fields, (function (i, param) {
                                      return React.createElement("li", {
                                                  key: String(i)
                                                }, Helpers$ReactHooksTemplate.str("" + (String(param[0]) + (" => " + (String(param[1]) + "")))));
                                    })));
                  })));
}

var make = Pages__Collection__Items;

exports.fetchItems = fetchItems;
exports.make = make;
/* react Not a pure module */
