// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var Belt_Array = require("bs-platform/lib/js/belt_Array.js");
var JMySon$ReactHooksTemplate = require("../../JMySon.bs.js");
var Helpers$ReactHooksTemplate = require("../../Helpers.bs.js");

function Pages__Collection__Overview$Box(Props) {
  var title = Props.title;
  var children = Props.children;
  var match = Props.className;
  var className = match !== undefined ? match : "";
  return React.createElement("article", {
              className: "content__overview__box " + className
            }, React.createElement("header", {
                  className: "content__overview__box__header"
                }, React.createElement("h1", {
                      className: "content__overview__box__header__title"
                    }, Helpers$ReactHooksTemplate.str(title))), React.createElement("section", {
                  className: "content__overview__box__body"
                }, children));
}

var Box = /* module */[/* make */Pages__Collection__Overview$Box];

function displaySchema(schema) {
  return Belt_Array.map(schema, (function (entry) {
                return React.createElement(React.Fragment, undefined, React.createElement("span", undefined, Helpers$ReactHooksTemplate.str("" + (String(entry[0]) + (" : " + (String(entry[1]) + ""))))), React.createElement("br", undefined));
              }));
}

function format_size(size) {
  var a = size[0].toString();
  return a + size[1];
}

function Pages__Collection__Overview(Props) {
  var modelName = Props.modelName;
  var match = Helpers$ReactHooksTemplate.useState(undefined);
  var setState = match[1];
  var state = match[0];
  React.useEffect((function () {
          fetch("/db_api/collection/" + (String(modelName) + "/overview")).then((function (prim) {
                        return prim.json();
                      })).then((function (x) {
                      return Promise.resolve(JMySon$ReactHooksTemplate.Decode[/* overview_response */4](x));
                    })).then((function (x) {
                    return Promise.resolve(x[/* data */0]);
                  })).then((function (x) {
                  return Promise.resolve(Curry._1(setState, x));
                }));
          return undefined;
        }), ([]));
  var tmp;
  if (state !== undefined) {
    var state$1 = state;
    tmp = React.createElement(React.Fragment, undefined, React.createElement(Pages__Collection__Overview$Box, {
              title: "stats",
              children: null
            }, React.createElement("span", {
                  className: "content__overview__box__body__text"
                }, Helpers$ReactHooksTemplate.str("count: " + String(state$1[/* stats */0][/* count */0]))), React.createElement("span", {
                  className: "content__overview__box__body__text"
                }, Helpers$ReactHooksTemplate.str("size: " + format_size(state$1[/* stats */0][/* size */1])))), React.createElement(Pages__Collection__Overview$Box, {
              title: "schema",
              children: displaySchema(state$1[/* schema */2])
            }));
  } else {
    tmp = React.createElement("span", undefined, Helpers$ReactHooksTemplate.str("loading..."));
  }
  return React.createElement("div", {
              className: "content__overview"
            }, tmp);
}

var make = Pages__Collection__Overview;

exports.Box = Box;
exports.displaySchema = displaySchema;
exports.format_size = format_size;
exports.make = make;
/* react Not a pure module */
