// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var Belt_Array = require("bs-platform/lib/js/belt_Array.js");
var Link$ReactHooksTemplate = require("../../components/Link.bs.js");
var JMySon$ReactHooksTemplate = require("../../JMySon.bs.js");
var Helpers$ReactHooksTemplate = require("../../Helpers.bs.js");

function make_action(href, text) {
  return /* record */[
          /* href */href,
          /* text */text
        ];
}

function Pages__Collection__Overview$Box(Props) {
  var title = Props.title;
  var children = Props.children;
  var match = Props.className;
  var className = match !== undefined ? match : "";
  var match$1 = Props.actions;
  var actions = match$1 !== undefined ? match$1 : /* array */[];
  return React.createElement("article", {
              className: "content__collection__box " + className
            }, React.createElement("header", {
                  className: "content__collection__box__header"
                }, React.createElement("h1", {
                      className: "content__collection__box__header__title"
                    }, Helpers$ReactHooksTemplate.str(title)), React.createElement("div", {
                      className: "content__collection__box__header__actions"
                    }, Belt_Array.mapWithIndex(actions, (function (i, action) {
                            return React.createElement(Link$ReactHooksTemplate.make, {
                                        children: Helpers$ReactHooksTemplate.str(action[/* text */1]),
                                        href: action[/* href */0],
                                        className: "content__collection__box__header__actions__link",
                                        key: String(i)
                                      });
                          })))), React.createElement("section", {
                  className: "content__collection__box__body"
                }, children));
}

var Box = /* module */[
  /* make_action */make_action,
  /* make */Pages__Collection__Overview$Box
];

function displaySchema(schema) {
  return Belt_Array.mapWithIndex(schema, (function (i, entry) {
                return React.createElement("tr", {
                            key: String(i),
                            className: "content__collection__box__body__table__row"
                          }, React.createElement("td", {
                                className: "content__collection__box__body__table__row__cell"
                              }, Helpers$ReactHooksTemplate.str(entry[0])), React.createElement("td", {
                                className: "content__collection__box__body__table__row__cell"
                              }, Helpers$ReactHooksTemplate.str(entry[1])));
              }));
}

function format_size(size) {
  var a = size[0].toString();
  return a + size[1];
}

function Pages__Collection__Overview(Props) {
  var modelName = Props.modelName;
  var match = Helpers$ReactHooksTemplate.useState(undefined);
  var setState = match[1];
  var state = match[0];
  React.useEffect((function () {
          fetch("/db_api/collection/" + (String(modelName) + "/overview")).then((function (prim) {
                        return prim.json();
                      })).then((function (x) {
                      return Promise.resolve(JMySon$ReactHooksTemplate.Decode[/* overview_response */4](x));
                    })).then((function (x) {
                    return Promise.resolve(x[/* data */0]);
                  })).then((function (x) {
                  return Promise.resolve(Curry._1(setState, x));
                }));
          return undefined;
        }), ([]));
  var tmp;
  if (state !== undefined) {
    var state$1 = state;
    tmp = React.createElement(React.Fragment, undefined, React.createElement(Pages__Collection__Overview$Box, {
              title: "stats",
              children: null,
              className: "content__collection__box--hor"
            }, React.createElement("span", {
                  className: "content__collection__box__body__text"
                }, Helpers$ReactHooksTemplate.str("count: " + String(state$1[/* stats */0][/* count */0]))), React.createElement("span", {
                  className: "content__collection__box__body__text"
                }, Helpers$ReactHooksTemplate.str("size: " + format_size(state$1[/* stats */0][/* size */1])))), React.createElement(Pages__Collection__Overview$Box, {
              title: "schema",
              children: React.createElement("table", {
                    className: "content__collection__box__body__table"
                  }, React.createElement("tbody", undefined, React.createElement("tr", {
                            className: "content__collection__box__body__table__head"
                          }, React.createElement("th", {
                                className: "content__collection__box__body__table__head__cell"
                              }, Helpers$ReactHooksTemplate.str("name")), React.createElement("th", {
                                className: "content__collection__box__body__table__head__cell"
                              }, Helpers$ReactHooksTemplate.str("type"))), displaySchema(state$1[/* schema */2]))),
              actions: /* array */[/* record */[
                  /* href */"/collection/" + (String(modelName) + "/schema/edit"),
                  /* text */"edit"
                ]]
            }));
  } else {
    tmp = React.createElement("span", undefined, Helpers$ReactHooksTemplate.str("loading..."));
  }
  return React.createElement("div", {
              className: "content__collection content__collection--overview"
            }, tmp);
}

var make = Pages__Collection__Overview;

exports.Box = Box;
exports.displaySchema = displaySchema;
exports.format_size = format_size;
exports.make = make;
/* react Not a pure module */
