// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

function Pages__Collection__Overview(Props) {
  Props.modelName;
  return React.createElement("div", {
              className: "content__posts"
            });
}

var make = Pages__Collection__Overview;

exports.make = make;
/* react Not a pure module */
