// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var Helpers$ReactHooksTemplate = require("../Helpers.bs.js");

function AuthLayout(Props) {
  var title = Props.title;
  var children = Props.children;
  var onSubmit = Props.onSubmit;
  var btnValue = Props.btnValue;
  return React.createElement("section", {
              className: "auth"
            }, React.createElement("img", {
                  className: "auth__img",
                  alt: "Photo by icon0.com from Pexels",
                  src: "/static/images/auth_bg_6.jpg"
                }), React.createElement("form", {
                  className: "auth__form",
                  action: "",
                  onSubmit: (function (e) {
                      e.preventDefault();
                      return Curry._1(onSubmit, e);
                    })
                }, React.createElement("h1", {
                      className: "auth__form__title"
                    }, Helpers$ReactHooksTemplate.str(title)), React.createElement("fieldset", {
                      className: "auth__form__fields"
                    }, children), React.createElement("input", {
                      className: "auth__form__btn auth__form__btn--submit",
                      type: "submit",
                      value: btnValue
                    })));
}

var make = AuthLayout;

exports.make = make;
/* react Not a pure module */
