// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var Icon$ReactHooksTemplate = require("./Icon.bs.js");

function Burger(Props) {
  var state = Props.state;
  var collapse = state[1];
  var collapsed = state[0];
  return React.createElement("button", {
              className: "nav__burger",
              onClick: (function (_e) {
                  return Curry._1(collapse, !collapsed);
                })
            }, React.createElement(Icon$ReactHooksTemplate.make, {
                  name: /* burger */-662434123
                }));
}

var make = Burger;

exports.make = make;
/* react Not a pure module */
