// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Belt_Array = require("bs-platform/lib/js/belt_Array.js");
var Helpers$ReactHooksTemplate = require("../Helpers.bs.js");

function Footer(Props) {
  var sections = /* array */[
    /* record */[
      /* title */"icons",
      /* links : array */[
        /* record */[
          /* text */"download source",
          /* href */"https://www.flaticon.com/"
        ],
        /* record */[
          /* text */"author: freepik",
          /* href */"https://www.freepik.com/"
        ]
      ]
    ],
    /* record */[
      /* title */"where to find me",
      /* links : array */[
        /* record */[
          /* text */"github",
          /* href */"https://github.com/DerivedMate"
        ],
        /* record */[
          /* text */"e-mail",
          /* href */"mailto: kemikspl@gmail.com?subject=feedback%20derivedcms"
        ]
      ]
    ]
  ];
  return React.createElement("footer", {
              className: "footer"
            }, Belt_Array.mapWithIndex(sections, (function (i, sec) {
                    return React.createElement("section", {
                                key: String(i),
                                className: "footer__col"
                              }, React.createElement("h4", {
                                    className: "footer__col__title"
                                  }, Helpers$ReactHooksTemplate.str(sec[/* title */0])), Belt_Array.mapWithIndex(sec[/* links */1], (function (j, link) {
                                      return React.createElement("a", {
                                                  key: String(j),
                                                  className: "footer__col__link",
                                                  href: link[/* href */1],
                                                  target: "_blank"
                                                }, Helpers$ReactHooksTemplate.str(link[/* text */0]));
                                    })));
                  })));
}

var make = Footer;

exports.make = make;
/* react Not a pure module */
