// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Helpers$ReactHooksTemplate = require("../Helpers.bs.js");

function Form__Input(Props) {
  var name = Props.name;
  var type_ = Props.type_;
  var placeholder = Props.placeholder;
  var label = Props.label;
  return React.createElement("label", {
              className: "auth__form__label",
              htmlFor: ""
            }, Helpers$ReactHooksTemplate.str(label), React.createElement("input", {
                  className: "auth__form__label__input",
                  id: name,
                  name: name,
                  placeholder: placeholder,
                  type: type_
                }));
}

var make = Form__Input;

exports.make = make;
/* react Not a pure module */
