// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

var burger = (require("@public/svg/burger.svg"));

var id = (require("@public/svg/id-card.svg"));

var folder = (require("@public/svg/folder.svg"));

function Icon(Props) {
  var name = Props.name;
  var logo = name !== -107972946 ? (
      name >= 23515 ? id : burger
    ) : folder;
  return React.createElement("div", {
              dangerouslySetInnerHTML: {
                __html: logo
              }
            });
}

var make = Icon;

exports.burger = burger;
exports.id = id;
exports.folder = folder;
exports.make = make;
/* burger Not a pure module */
