// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Nav$ReactHooksTemplate = require("./Nav.bs.js");
var Icon$ReactHooksTemplate = require("./Icon.bs.js");
var Helpers$ReactHooksTemplate = require("../Helpers.bs.js");

function Layout(Props) {
  var children = Props.children;
  var match = Helpers$ReactHooksTemplate.useState(false);
  var collapsed = match[0];
  return React.createElement("section", {
              className: /* array */[
                  "layout",
                  collapsed ? "collapsed" : ""
                ].join(" ")
            }, React.createElement(Nav$ReactHooksTemplate.make, {
                  state: /* tuple */[
                    collapsed,
                    match[1]
                  ],
                  children: null
                }, React.createElement(Nav$ReactHooksTemplate.Item[/* make */0], {
                      href: "#",
                      icon: React.createElement(Icon$ReactHooksTemplate.make, {
                            name: /* id */23515
                          }),
                      children: Helpers$ReactHooksTemplate.str("Hello")
                    }), React.createElement(Nav$ReactHooksTemplate.Submenu[/* make */0], {
                      children: React.createElement(Nav$ReactHooksTemplate.Item[/* make */0], {
                            href: "#",
                            icon: React.createElement(Icon$ReactHooksTemplate.make, {
                                  name: /* id */23515
                                }),
                            children: Helpers$ReactHooksTemplate.str("there")
                          }),
                      href: "#",
                      icon: React.createElement(Icon$ReactHooksTemplate.make, {
                            name: /* burger */-662434123
                          }),
                      rootContent: Helpers$ReactHooksTemplate.str("Hello"),
                      nItems: 1
                    }), React.createElement(Nav$ReactHooksTemplate.Submenu[/* make */0], {
                      children: null,
                      href: "#",
                      icon: React.createElement(Icon$ReactHooksTemplate.make, {
                            name: /* burger */-662434123
                          }),
                      rootContent: Helpers$ReactHooksTemplate.str("Hello"),
                      nItems: 3
                    }, React.createElement(Nav$ReactHooksTemplate.Item[/* make */0], {
                          href: "#",
                          icon: React.createElement(Icon$ReactHooksTemplate.make, {
                                name: /* id */23515
                              }),
                          children: Helpers$ReactHooksTemplate.str("there")
                        }), React.createElement(Nav$ReactHooksTemplate.Item[/* make */0], {
                          href: "#",
                          icon: React.createElement(Icon$ReactHooksTemplate.make, {
                                name: /* id */23515
                              }),
                          children: Helpers$ReactHooksTemplate.str("good")
                        }), React.createElement(Nav$ReactHooksTemplate.Item[/* make */0], {
                          href: "#",
                          icon: React.createElement(Icon$ReactHooksTemplate.make, {
                                name: /* id */23515
                              }),
                          children: Helpers$ReactHooksTemplate.str("sir")
                        }))), React.createElement("section", {
                  className: "content"
                }, children));
}

var make = Layout;

exports.make = make;
/* react Not a pure module */
