// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var Helpers$ReactHooksTemplate = require("../Helpers.bs.js");

function Modal$Empty(Props) {
  var children = Props.children;
  var match = Props.className;
  var className = match !== undefined ? match : "";
  var onAccept = Props.onAccept;
  return React.createElement("form", {
              className: "modal",
              onSubmit: (function (e) {
                  e.preventDefault();
                  return Curry._1(onAccept, e);
                })
            }, React.createElement("field", {
                  className: "modal__body " + className
                }, children), React.createElement("nav", {
                  className: "modal__nav"
                }, React.createElement("button", {
                      className: "modal__nav__btn"
                    }, Helpers$ReactHooksTemplate.str("cancel")), React.createElement("button", {
                      className: "modal__nav__btn",
                      type: "submit"
                    }, Helpers$ReactHooksTemplate.str("accept"))));
}

var Empty = /* module */[/* make */Modal$Empty];

function Modal$TwoFields(Props) {
  var labels = Props.labels;
  var onAccept = Props.onAccept;
  var l2 = labels[1];
  var l1 = labels[0];
  return React.createElement(Modal$Empty, {
              children: null,
              onAccept: (function (e) {
                  return Curry._1(onAccept, /* array */[
                              e.currentTarget.l1,
                              e.currentTarget.l2
                            ]);
                })
            }, React.createElement("label", {
                  className: "modal__body__label",
                  htmlFor: l1
                }, Helpers$ReactHooksTemplate.str(l1)), React.createElement("input", {
                  className: "model__body__input",
                  name: l1,
                  type: "text"
                }), React.createElement("label", {
                  className: "modal__body__label",
                  htmlFor: l2
                }, Helpers$ReactHooksTemplate.str(l2)), React.createElement("input", {
                  className: "model__body__input",
                  name: l2,
                  type: "text"
                }));
}

var TwoFields = /* module */[/* make */Modal$TwoFields];

function Modal$OneField(Props) {
  var label = Props.label;
  var onAccept = Props.onAccept;
  return React.createElement(Modal$Empty, {
              children: null,
              onAccept: (function (e) {
                  return Curry._1(onAccept, e.currentTarget.label);
                })
            }, React.createElement("label", {
                  className: "modal__body__label",
                  htmlFor: label
                }, Helpers$ReactHooksTemplate.str(label)), React.createElement("input", {
                  className: "model__body__input",
                  name: label,
                  type: "text"
                }));
}

var OneField = /* module */[/* make */Modal$OneField];

exports.Empty = Empty;
exports.TwoFields = TwoFields;
exports.OneField = OneField;
/* react Not a pure module */
