// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var Burger$ReactHooksTemplate = require("./Burger.bs.js");
var Helpers$ReactHooksTemplate = require("../Helpers.bs.js");

function Nav$Item(Props) {
  var href = Props.href;
  var icon = Props.icon;
  var children = Props.children;
  var onClick = Props.onClick;
  var className = Props.className;
  return React.createElement("li", {
              className: /* array */[
                  "nav__list__item",
                  className !== undefined ? className : ""
                ].join(" "),
              onClick: (function (e) {
                  if (onClick !== undefined) {
                    return Curry._1(onClick, e);
                  } else {
                    return /* () */0;
                  }
                })
            }, React.createElement("a", {
                  className: "nav__list__item__link",
                  href: href
                }, React.createElement("figure", {
                      className: "nav__list__item__link__icon"
                    }, icon), React.createElement("span", {
                      className: "nav__list__item__link__text"
                    }, children)));
}

var Item = /* module */[/* make */Nav$Item];

function Nav$Submenu(Props) {
  var children = Props.children;
  var href = Props.href;
  var icon = Props.icon;
  var rootContent = Props.rootContent;
  var nItems = Props.nItems;
  var match = Helpers$ReactHooksTemplate.useState(false);
  var setopen = match[1];
  var isopen = match[0];
  var style = ReactDOMRe.Style[/* unsafeAddProp */1]({ }, "--n", String(nItems));
  return React.createElement("li", {
              className: /* array */[
                  "nav__submenu",
                  isopen ? "nav__submenu--open" : ""
                ].join(" "),
              style: style
            }, React.createElement(Nav$Item, {
                  href: href,
                  icon: icon,
                  children: rootContent,
                  onClick: (function (param) {
                      return Curry._1(setopen, !isopen);
                    }),
                  className: "nav__submenu__root"
                }), React.createElement("ul", {
                  className: "nav__submenu__list"
                }, children));
}

var Submenu = /* module */[/* make */Nav$Submenu];

function Nav(Props) {
  var state = Props.state;
  var children = Props.children;
  var collapsed = state[0];
  return React.createElement("nav", {
              className: /* array */[
                  "nav",
                  collapsed ? "nav--collapsed" : ""
                ].join(" ")
            }, React.createElement(Burger$ReactHooksTemplate.make, {
                  state: /* tuple */[
                    collapsed,
                    state[1]
                  ]
                }), React.createElement("ul", {
                  className: "nav__list"
                }, children));
}

var make = Nav;

exports.Item = Item;
exports.Submenu = Submenu;
exports.make = make;
/* react Not a pure module */
